Repository Team-Recordy/Recordy-Server, pull requests merged in 2024-06, with the labels that each got.

#3 [feat] 사용자 로그인 유즈케이스 구현 준비
  build.gradle
  src/main/java/org/recordy/server/auth/domain/Auth.java
  src/main/java/org/recordy/server/auth/domain/AuthEntity.java
  src/main/java/org/recordy/server/auth/domain/AuthPlatform.java
  src/main/java/org/recordy/server/auth/domain/AuthToken.java
  src/main/java/org/recordy/server/auth/domain/usecase/AuthSignIn.java
  src/main/java/org/recordy/server/auth/repository/AuthRepository.java
  src/main/java/org/recordy/server/auth/repository/impl/AuthRedisRepository.java
  src/main/java/org/recordy/server/auth/repository/impl/AuthRepositoryImpl.java
  src/main/java/org/recordy/server/auth/service/AuthPlatformService.java
  src/main/java/org/recordy/server/auth/service/AuthPlatformServiceFactory.java
  src/main/java/org/recordy/server/auth/service/AuthService.java
  src/main/java/org/recordy/server/auth/service/AuthTokenService.java
  src/main/java/org/recordy/server/auth/service/dto/AuthTokenValidationResult.java
  src/main/java/org/recordy/server/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/apple/AuthApplePlatformServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImpl.java
  src/main/java/org/recordy/server/common/config/FeignClientConfig.java
  src/main/java/org/recordy/server/common/config/JpaEntityAuditingConfig.java
  src/main/java/org/recordy/server/common/domain/JpaMetaInfoEntity.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/controller/dto/request/UserSignInRequest.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserSignInResponse.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/main/java/org/recordy/server/user/domain/UserStatus.java
  src/main/java/org/recordy/server/user/repository/UserRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserJpaRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserRepositoryImpl.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/auth/domain/AuthEntityTest.java
  src/test/java/org/recordy/server/auth/domain/usecase/AuthSignInTest.java
  src/test/java/org/recordy/server/auth/repository/AuthRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/auth/service/AuthServiceIntegrationTest.java
  src/test/java/org/recordy/server/auth/service/AuthServiceTest.java
  src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
  src/test/java/org/recordy/server/auth/service/impl/apple/AuthApplePlatformServiceImplTest.java
  src/test/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImplTest.java
  src/test/java/org/recordy/server/common/domain/JpaMetaInfoEntityTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/auth/FakeAuthApplePlatformServiceImpl.java
  src/test/java/org/recordy/server/mock/auth/FakeAuthKakaoPlatformServiceImpl.java
  src/test/java/org/recordy/server/mock/auth/FakeAuthRepository.java
  src/test/java/org/recordy/server/mock/user/FakeUserRepository.java
  src/test/java/org/recordy/server/user/controller/UserControllerIntegrationTest.java
  src/test/java/org/recordy/server/user/controller/UserControllerTest.java
  src/test/java/org/recordy/server/user/controller/dto/response/UserSignInResponseTest.java
  src/test/java/org/recordy/server/user/domain/UserEntityTest.java
  src/test/java/org/recordy/server/user/repository/UserRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/user/service/UserServiceIntegrationTest.java
  src/test/java/org/recordy/server/user/service/UserServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
  src/test/resources/sql/user-repository-test-clean.sql
  src/test/resources/sql/user-repository-test-data.sql
  src/test/resources/sql/user-service-test-clean.sql
  src/test/resources/sql/user-service-test-data.sql
Labels: feat 🔥, test 🧠

#9 [feat] UserController 스웨거
  build.gradle
  src/main/java/org/recordy/server/common/config/SwaggerConfig.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
Labels: feat 🔥

#14 [settings] 블루-그린 배포를 위해 Github Actions yml 파일 수정, 배포 쉘 스크립트 파일 및 도커 컴포즈 파일 작성
  .github/workflows/DOCKER-CI-CD.yml
  docker-compse.yml
  scripts/deploy.sh
Labels: settings ⚙️

#15 [feat] Spring Security 1차 도입
  build.gradle
  src/main/java/org/recordy/server/auth/security/UserAuthentication.java
  src/main/java/org/recordy/server/auth/service/impl/AuthTokenServiceImpl.java
Labels: feat 🔥
