Repository Team-Recordy/Recordy-Server, pull requests merged in 2024-07, with the labels that each got.

#13 [feat] Apple Login 구현
  src/main/java/org/recordy/server/auth/exception/AuthException.java
  src/main/java/org/recordy/server/auth/service/impl/apple/AppleClaimsValidator.java
  src/main/java/org/recordy/server/auth/service/impl/apple/AppleFeignClient.java
  src/main/java/org/recordy/server/auth/service/impl/apple/AppleIdentityTokenParser.java
  src/main/java/org/recordy/server/auth/service/impl/apple/ApplePublicKey.java
  src/main/java/org/recordy/server/auth/service/impl/apple/ApplePublicKeyGenerator.java
  src/main/java/org/recordy/server/auth/service/impl/apple/ApplePublicKeys.java
  src/main/java/org/recordy/server/auth/service/impl/apple/AuthApplePlatformServiceImpl.java
  src/main/java/org/recordy/server/common/exception/RecordyException.java
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
Labels: feat 🔥

#21 [feat] Spring Security 2차 도입
  src/main/java/org/recordy/server/ServerApplication.java
  src/main/java/org/recordy/server/auth/exception/AuthException.java
  src/main/java/org/recordy/server/auth/security/TokenAuthenticationFilter.java
  src/main/java/org/recordy/server/auth/security/handler/AuthFilterExceptionHandler.java
  src/main/java/org/recordy/server/auth/security/handler/UndefinedAccessHandler.java
  src/main/java/org/recordy/server/auth/service/AuthTokenService.java
  src/main/java/org/recordy/server/auth/service/impl/AuthPlatformServiceFactory.java
  src/main/java/org/recordy/server/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/kakao/KakaoFeignClient.java
  src/main/java/org/recordy/server/auth/service/impl/kakao/KakaoPlatformInfo.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenGenerator.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenParser.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenSigningKeyProvider.java
  src/main/java/org/recordy/server/common/config/SecurityConfig.java
  src/main/java/org/recordy/server/common/dto/response/ErrorResponse.java
  src/main/java/org/recordy/server/common/exception/CommonException.java
  src/main/java/org/recordy/server/common/exception/RecordyException.java
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/test/java/org/recordy/server/auth/security/TokenAuthenticationFilterTest.java
  src/test/java/org/recordy/server/auth/security/handler/AuthFilterExceptionHandlerTest.java
  src/test/java/org/recordy/server/auth/security/handler/UndefinedAccessHandlerTest.java
  src/test/java/org/recordy/server/auth/service/AuthServiceIntegrationTest.java
  src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
  src/test/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImplTest.java
  src/test/java/org/recordy/server/auth/service/impl/token/AuthTokenGeneratorTest.java
  src/test/java/org/recordy/server/auth/service/impl/token/AuthTokenParserTest.java
  src/test/java/org/recordy/server/auth/service/impl/token/AuthTokenSigningKeyProviderTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/auth/FakeAuthKakaoPlatformServiceImpl.java
  src/test/java/org/recordy/server/mock/auth/FakeKakaoFeignClient.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: feat 🔥, test 🧠

#20 [feat] 닉네임 중복확인
  recordy.mv.db
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/main/java/org/recordy/server/user/exception/UserException.java
  src/main/java/org/recordy/server/user/repository/UserRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserJpaRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserRepositoryImpl.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: feat 🔥

#23 [feat] 공통적 예외를 위한 핸들러 추가
  src/main/java/org/recordy/server/common/dto/response/ErrorResponse.java
  src/main/java/org/recordy/server/common/handler/GlobalExceptionHandler.java
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
Labels: feat 🔥

#24 [feat] 토큰 리프레시 및 로그아웃 구현
  src/main/java/org/recordy/server/auth/domain/AuthEntity.java
  src/main/java/org/recordy/server/auth/exception/AuthException.java
  src/main/java/org/recordy/server/auth/repository/AuthRepository.java
  src/main/java/org/recordy/server/auth/repository/impl/AuthRedisRepository.java
  src/main/java/org/recordy/server/auth/repository/impl/AuthRepositoryImpl.java
  src/main/java/org/recordy/server/auth/service/AuthTokenService.java
  src/main/java/org/recordy/server/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/common/exception/RecordyException.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserReissueTokenResponse.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/auth/repository/AuthRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/auth/FakeAuthRepository.java
  src/test/java/org/recordy/server/mock/user/FakeUserRepository.java
  src/test/java/org/recordy/server/user/controller/UserControllerTest.java
  src/test/java/org/recordy/server/user/service/UserServiceTest.java
Labels: feat 🔥, test 🧠

#31 [feat] 회원 등록
  recordy.mv.db
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/controller/dto/request/TermsAgreement.java
  src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/main/java/org/recordy/server/user/domain/UserStatus.java
  src/main/java/org/recordy/server/user/repository/UserRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserJpaRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserRepositoryImpl.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: feat 🔥

#40 [fix] 테스트 통과하도록 수정 및 테스트 보강
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/record/service/impl/FileServiceImpl.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
  src/test/java/org/recordy/server/keyword/repository/KeywordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/mock/user/FakeUserRepository.java
  src/test/java/org/recordy/server/record/repository/RecordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/user/controller/UserControllerTest.java
  src/test/java/org/recordy/server/user/repository/UserRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/user/service/UserServiceTest.java
  src/test/java/org/recordy/server/util/db/DatabaseCleaner.java
  src/test/java/org/recordy/server/util/db/DatabaseCleanerExtension.java
  src/test/java/org/recordy/server/util/db/IntegrationTest.java
  src/test/resources/sql/record-repository-test-data.sql
  src/test/resources/sql/user-repository-test-data.sql
Labels: fix 🛠️

#37 [feat] S3 설정 추가
  build.gradle
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
  src/main/java/org/recordy/server/external/config/S3Config.java
  src/main/java/org/recordy/server/external/controller/S3TestApi.java
  src/main/java/org/recordy/server/external/controller/S3TestController.java
  src/main/java/org/recordy/server/external/exception/ExternalException.java
  src/main/java/org/recordy/server/external/service/S3Service.java
  src/main/java/org/recordy/server/external/service/impl/S3ServiceImpl.java
  src/main/java/org/recordy/server/record/exception/RecordException.java
  src/main/java/org/recordy/server/record/service/impl/FileServiceImpl.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/test/java/org/recordy/server/external/controller/S3TestControllerTest.java
  src/test/java/org/recordy/server/external/service/S3ServiceTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
Labels: feat 🔥, test 🧠

#44 [feat] 북마크 도메인 정의
  README.md
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
  src/main/java/org/recordy/server/record/exception/RecordException.java
  src/main/java/org/recordy/server/record/repository/RecordRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/domain/Bookmark.java
  src/main/java/org/recordy/server/record_stat/domain/BookmarkEntity.java
  src/main/java/org/recordy/server/record_stat/repository/BookmarkJpaRepository.java
  src/main/java/org/recordy/server/record_stat/repository/BookmarkQueryDslRepository.java
  src/main/java/org/recordy/server/record_stat/repository/BookmarkRepository.java
  src/main/java/org/recordy/server/record_stat/repository/BookmarkRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/service/RecordStatService.java
  src/main/java/org/recordy/server/record_stat/service/impl/RecordStatServiceImpl.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/bookmark/FakeBookmarkRepository.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/record_stat/domain/BookmarkEntityTest.java
  src/test/java/org/recordy/server/record_stat/repository/BookmarkRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record_stat/service/RecordStatServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
  src/test/resources/sql/bookmark-repository-test-clean.sql
  src/test/resources/sql/bookmark-repository-test-data.sql
Labels: feat 🔥, test 🧠

#38 [feat] RecordService 1차 구현
  recordy.mv.db
  src/main/java/org/recordy/server/common/message/ErrorMessage.java
  src/main/java/org/recordy/server/keyword/domain/Keyword.java
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/controller/dto/FileUrl.java
  src/main/java/org/recordy/server/record/controller/dto/RecordCreateRequest.java
  src/main/java/org/recordy/server/record/domain/Record.java
  src/main/java/org/recordy/server/record/domain/RecordEntity.java
  src/main/java/org/recordy/server/record/domain/usecase/RecordCreate.java
  src/main/java/org/recordy/server/record/exception/RecordException.java
  src/main/java/org/recordy/server/record/repository/RecordRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record/service/FileService.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/FileServiceImpl.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/test/java/org/recordy/server/mock/record/FakeFileService.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/record/domain/RecordEntityTest.java
  src/test/java/org/recordy/server/record/repository/RecordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record/service/RecordServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
  src/test/resources/sql/record-repository-test-data.sql
  test.mv.db
Labels: feat 🔥, test 🧠

#60 [refactor] RecordController, UserController 리팩토링
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/domain/File.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/repository/BookmarkRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkJpaRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/service/impl/RecordStatServiceImpl.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/test/java/org/recordy/server/mock/bookmark/FakeBookmarkRepository.java
  src/test/java/org/recordy/server/record_stat/repository/BookmarkRepositoryIntegrationTest.java
Labels: refactor ♻️, fix 🛠️

#53 [feat] 구독 도메인 정의
  src/main/java/org/recordy/server/record/domain/RecordEntity.java
  src/main/java/org/recordy/server/record/repository/RecordRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/subscribe/domain/Subscribe.java
  src/main/java/org/recordy/server/subscribe/domain/SubscribeEntity.java
  src/main/java/org/recordy/server/subscribe/domain/usecase/SubscribeCreate.java
  src/main/java/org/recordy/server/subscribe/repository/SubscribeRepository.java
  src/main/java/org/recordy/server/subscribe/repository/impl/SubscribeJpaRepository.java
  src/main/java/org/recordy/server/subscribe/repository/impl/SubscribeQueryDslRepository.java
  src/main/java/org/recordy/server/subscribe/repository/impl/SubscribeRepositoryImpl.java
  src/main/java/org/recordy/server/subscribe/service/SubscribeService.java
  src/main/java/org/recordy/server/subscribe/service/impl/SubscribeServiceImpl.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/record/repository/RecordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/subscribe/domain/SubscribeEntityTest.java
  src/test/java/org/recordy/server/subscribe/repository/SubscribeRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
  src/test/resources/sql/subscribe-repository-test-data.sql
Labels: feat 🔥, test 🧠

#63 [fix] 충돌 에러 해결
  src/main/java/org/recordy/server/record_stat/repository/BookmarkRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkQueryDslRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/service/impl/RecordStatServiceImpl.java
  src/test/java/org/recordy/server/mock/bookmark/FakeBookmarkRepository.java
  src/test/java/org/recordy/server/record_stat/repository/BookmarkRepositoryIntegrationTest.java
Labels: fix 🛠️

#58 [docs] swagger 명세서 세세히 작성
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  test.mv.db
Labels: docs 📓

#64 [fix] 무한 스크롤 레코드 리스트 수정
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/controller/dto/response/RecordInfo.java
  src/main/java/org/recordy/server/record/controller/dto/response/RecordInfoWithBookmark.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatApi.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/main/java/org/recordy/server/record_stat/repository/BookmarkRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkJpaRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/service/RecordStatService.java
  src/main/java/org/recordy/server/record_stat/service/impl/RecordStatServiceImpl.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/bookmark/FakeBookmarkRepository.java
  src/test/java/org/recordy/server/record/service/RecordServiceTest.java
  src/test/java/org/recordy/server/record_stat/repository/BookmarkRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record_stat/repository/impl/ViewRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record_stat/service/RecordStatServiceTest.java
Labels: fix 🛠️

#71 [feat] 구독 관련 controller 작성
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/main/java/org/recordy/server/subscribe/repository/SubscribeRepository.java
  src/main/java/org/recordy/server/subscribe/repository/impl/SubscribeQueryDslRepository.java
  src/main/java/org/recordy/server/subscribe/repository/impl/SubscribeRepositoryImpl.java
  src/main/java/org/recordy/server/subscribe/service/SubscribeService.java
  src/main/java/org/recordy/server/subscribe/service/impl/SubscribeServiceImpl.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserAuthApi.java
  src/main/java/org/recordy/server/user/controller/UserAuthController.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserInfo.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserInfoWithFollowing.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/subscribe/FakeSubscribeRepository.java
  src/test/java/org/recordy/server/subscribe/service/SubscribeServiceTest.java
  src/test/java/org/recordy/server/user/controller/UserAuthControllerIntegrationTest.java
  src/test/java/org/recordy/server/user/controller/UserAuthControllerTest.java
Labels: feat 🔥

#72 [feat] 전체 동영상 페이지네이션 api 구현
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/controller/dto/response/RecordInfoWithBookmark.java
  src/main/java/org/recordy/server/record/repository/RecordRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/main/java/org/recordy/server/record_stat/service/RecordStatService.java
  src/main/java/org/recordy/server/record_stat/service/impl/RecordStatServiceImpl.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
Labels: feat 🔥

#77 [feat] API 완성 전 마무리 작업
  src/main/java/org/recordy/server/keyword/domain/Keyword.java
  src/main/java/org/recordy/server/keyword/domain/KeywordEntity.java
  src/main/java/org/recordy/server/record/controller/dto/request/RecordCreateRequest.java
  src/main/java/org/recordy/server/record/domain/usecase/RecordCreate.java
  src/main/java/org/recordy/server/record/repository/RecordRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserInfo.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/main/java/org/recordy/server/user/domain/usecase/UserProfile.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/keyword/domain/KeywordTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/auth/FakeKakaoFeignClient.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/mock/user/FakeUserRepository.java
  src/test/java/org/recordy/server/record/domain/UploadEntityTest.java
  src/test/java/org/recordy/server/record/repository/RecordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/user/domain/UserTest.java
  src/test/java/org/recordy/server/user/service/UserServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
  src/test/resources/sql/bookmark-repository-test-data.sql
  src/test/resources/sql/keyword-repository-test-data.sql
  src/test/resources/sql/record-repository-test-data.sql
  src/test/resources/sql/view-repository-test-data.sql
Labels: feat 🔥, test 🧠

#76 [refactor] cursor 값 수정 로직 작성
  src/main/java/org/recordy/server/common/util/QueryDslUtils.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/BookmarkQueryDslRepository.java
  src/main/java/org/recordy/server/subscribe/repository/impl/SubscribeQueryDslRepository.java
Labels: refactor ♻️

#68 [ docs] RecrodStat api 명세서
  src/main/java/org/recordy/server/record_stat/controller/RecordStatApi.java
Labels: docs 📓

#75 [refactor] S3 presignedUrl 적용해서 createdRecord 수정
  src/main/java/org/recordy/server/keyword/domain/Keyword.java
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/controller/dto/request/RecordCreateRequest.java
  src/main/java/org/recordy/server/record/domain/File.java
  src/main/java/org/recordy/server/record/domain/Record.java
  src/main/java/org/recordy/server/record/domain/usecase/RecordCreate.java
  src/main/java/org/recordy/server/record/service/S3Service.java
  src/main/java/org/recordy/server/record/service/dto/FileUrl.java
  src/main/java/org/recordy/server/record/service/impl/FileServiceImpl.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/record/service/impl/S3ServiceImpl.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/record/FakeFileService.java
Labels: refactor ♻️

#83 [fix] merge에러 수정(#82)
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
Labels: fix 🛠️

#54 [refactor] Auth 도메인 리팩토링 및 테스트 보강
  src/main/java/org/recordy/server/auth/domain/AuthPlatform.java
  src/main/java/org/recordy/server/auth/repository/AuthRepository.java
  src/main/java/org/recordy/server/auth/repository/impl/AuthRedisRepository.java
  src/main/java/org/recordy/server/auth/repository/impl/AuthRepositoryImpl.java
  src/main/java/org/recordy/server/auth/security/filter/TokenAuthenticationFilter.java
  src/main/java/org/recordy/server/auth/security/handler/UndefinedAccessHandler.java
  src/main/java/org/recordy/server/auth/security/resolver/AccessTokenArgumentResolver.java
  src/main/java/org/recordy/server/auth/security/resolver/UserId.java
  src/main/java/org/recordy/server/auth/service/dto/AuthTokenValidationResult.java
  src/main/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/common/config/SecurityConfig.java
  src/main/java/org/recordy/server/common/config/WebConfig.java
  src/test/java/org/recordy/server/auth/repository/AuthRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/auth/security/filter/TokenAuthenticationFilterTest.java
  src/test/java/org/recordy/server/auth/security/handler/AuthFilterExceptionHandlerTest.java
  src/test/java/org/recordy/server/auth/security/resolver/AccessTokenArgumentResolverTest.java
  src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
Labels: refactor ♻️

#86 [refactor] recordInfo 반환타입 수정
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/controller/dto/response/RecordInfo.java
  src/main/java/org/recordy/server/record/controller/dto/response/RecordInfoWithBookmark.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
Labels: refactor ♻️

#80 [feat] 유저 프로필 Controller 작성
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/main/java/org/recordy/server/user/domain/usecase/UserProfile.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/user/domain/UserEntityTest.java
  src/test/java/org/recordy/server/user/service/UserServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: feat 🔥

#88 [refactor] 무한스크롤 반환 타입 수정
  src/main/java/org/recordy/server/common/dto/response/CursorBasePaginatedResponse.java
  src/main/java/org/recordy/server/common/dto/response/PaginatedResponse.java
  src/main/java/org/recordy/server/common/util/QueryDslUtils.java
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatApi.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
Labels: refactor ♻️

#85 [refactor] bookmark, follow 등록/삭제 API 엔드포인트 통일
  src/main/java/org/recordy/server/auth/service/AuthTokenService.java
  src/main/java/org/recordy/server/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/recordy/server/auth/service/impl/token/AuthTokenServiceImpl.java
  src/main/java/org/recordy/server/keyword/controller/KeywordApi.java
  src/main/java/org/recordy/server/keyword/controller/KeywordController.java
  src/main/java/org/recordy/server/keyword/domain/Keyword.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatApi.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/main/java/org/recordy/server/record_stat/domain/usecase/Preference.java
  src/main/java/org/recordy/server/record_stat/service/RecordStatService.java
  src/main/java/org/recordy/server/record_stat/service/impl/RecordStatServiceImpl.java
  src/main/java/org/recordy/server/subscribe/service/SubscribeService.java
  src/main/java/org/recordy/server/subscribe/service/impl/SubscribeServiceImpl.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/test/java/org/recordy/server/auth/service/impl/kakao/AuthKakaoPlatformServiceImplTest.java
  src/test/java/org/recordy/server/keyword/domain/KeywordTest.java
  src/test/java/org/recordy/server/mock/auth/FakeKakaoFeignClient.java
  src/test/java/org/recordy/server/record_stat/service/RecordStatServiceTest.java
  src/test/java/org/recordy/server/subscribe/service/SubscribeServiceTest.java
  src/test/java/org/recordy/server/user/controller/UserAuthControllerTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: refactor ♻️, test 🧠

#90 [refactor] signIn시 userId도 함께 전달하도록 수정
  src/main/java/org/recordy/server/auth/domain/Auth.java
  src/main/java/org/recordy/server/auth/domain/AuthEntity.java
  src/main/java/org/recordy/server/auth/service/impl/AuthServiceImpl.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserSignInResponse.java
  src/test/java/org/recordy/server/auth/service/AuthTokenServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: refactor ♻️

#92 [refactor] API 엔드포인트 url에 맞춘 컨트롤러 리팩토링
  src/main/java/org/recordy/server/bookmark/controller/BookmarkApi.java
  src/main/java/org/recordy/server/bookmark/controller/BookmarkController.java
  src/main/java/org/recordy/server/bookmark/domain/Bookmark.java
  src/main/java/org/recordy/server/bookmark/domain/BookmarkEntity.java
  src/main/java/org/recordy/server/bookmark/repository/BookmarkRepository.java
  src/main/java/org/recordy/server/bookmark/repository/impl/BookmarkJpaRepository.java
  src/main/java/org/recordy/server/bookmark/repository/impl/BookmarkQueryDslRepository.java
  src/main/java/org/recordy/server/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/org/recordy/server/bookmark/service/BookmarkService.java
  src/main/java/org/recordy/server/bookmark/service/impl/BookmarkServiceImpl.java
  src/main/java/org/recordy/server/preference/controller/PreferenceApi.java
  src/main/java/org/recordy/server/preference/controller/PreferenceController.java
  src/main/java/org/recordy/server/preference/domain/usecase/Preference.java
  src/main/java/org/recordy/server/preference/service/PreferenceService.java
  src/main/java/org/recordy/server/preference/service/impl/PreferenceServiceImpl.java
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/domain/RecordEntity.java
  src/main/java/org/recordy/server/record/repository/impl/RecordQueryDslRepository.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatApi.java
  src/main/java/org/recordy/server/record_stat/controller/RecordStatController.java
  src/main/java/org/recordy/server/record_stat/repository/ViewRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/ViewQueryDslRepository.java
  src/main/java/org/recordy/server/record_stat/repository/impl/ViewRepositoryImpl.java
  src/main/java/org/recordy/server/record_stat/service/RecordStatService.java
  src/main/java/org/recordy/server/user/controller/UserApi.java
  src/main/java/org/recordy/server/view/domain/View.java
  src/main/java/org/recordy/server/view/domain/ViewEntity.java
  src/main/java/org/recordy/server/view/repository/ViewRepository.java
  src/main/java/org/recordy/server/view/repository/impl/ViewJpaRepository.java
  src/main/java/org/recordy/server/view/repository/impl/ViewQueryDslRepository.java
  src/main/java/org/recordy/server/view/repository/impl/ViewRepositoryImpl.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/bookmark/FakeBookmarkRepository.java
  src/test/java/org/recordy/server/mock/view/FakeViewRepository.java
  src/test/java/org/recordy/server/record/repository/RecordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record_stat/domain/BookmarkEntityTest.java
  src/test/java/org/recordy/server/record_stat/repository/BookmarkRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record_stat/repository/impl/ViewRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record_stat/service/RecordStatServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: refactor ♻️

#95 [refactor] preference response 타입 변환
  src/main/java/org/recordy/server/preference/domain/usecase/Preference.java
Labels: refactor ♻️

#99 [fix] 북마크 페이지네이션 작동하도록 수정
  src/main/java/org/recordy/server/bookmark/controller/BookmarkApi.java
  src/main/java/org/recordy/server/bookmark/controller/BookmarkController.java
  src/main/java/org/recordy/server/bookmark/repository/BookmarkRepository.java
  src/main/java/org/recordy/server/bookmark/repository/impl/BookmarkJpaRepository.java
  src/main/java/org/recordy/server/bookmark/repository/impl/BookmarkQueryDslRepository.java
  src/main/java/org/recordy/server/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/org/recordy/server/bookmark/service/BookmarkService.java
  src/main/java/org/recordy/server/bookmark/service/impl/BookmarkServiceImpl.java
  src/main/java/org/recordy/server/record/controller/RecordApi.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/controller/dto/response/BookmarkedRecord.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/test/java/org/recordy/server/mock/bookmark/FakeBookmarkRepository.java
Labels: fix 🛠️

#96 [refactor] User 도메인 리팩토링 및 테스트 보강
  src/main/java/org/recordy/server/record/domain/UploadEntity.java
  src/main/java/org/recordy/server/record/repository/impl/RecordRepositoryImpl.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/user/controller/UserAuthController.java
  src/main/java/org/recordy/server/user/controller/UserController.java
  src/main/java/org/recordy/server/user/controller/dto/request/UserSignUpRequest.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserInfo.java
  src/main/java/org/recordy/server/user/controller/dto/response/UserInfoWithFollowing.java
  src/main/java/org/recordy/server/user/domain/TermsAgreement.java
  src/main/java/org/recordy/server/user/domain/User.java
  src/main/java/org/recordy/server/user/domain/UserEntity.java
  src/main/java/org/recordy/server/user/domain/UserStatus.java
  src/main/java/org/recordy/server/user/domain/usecase/UserProfile.java
  src/main/java/org/recordy/server/user/domain/usecase/UserSignUp.java
  src/main/java/org/recordy/server/user/repository/UserRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserJpaRepository.java
  src/main/java/org/recordy/server/user/repository/impl/UserRepositoryImpl.java
  src/main/java/org/recordy/server/user/service/UserService.java
  src/main/java/org/recordy/server/user/service/impl/UserServiceImpl.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/auth/FakeKakaoFeignClient.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/mock/user/FakeUserRepository.java
  src/test/java/org/recordy/server/user/controller/UserAuthControllerTest.java
  src/test/java/org/recordy/server/user/controller/dto/request/TermsAgreementTest.java
  src/test/java/org/recordy/server/user/controller/dto/response/UserInfoTest.java
  src/test/java/org/recordy/server/user/controller/dto/response/UserInfoWithFollowingTest.java
  src/test/java/org/recordy/server/user/domain/UserEntityTest.java
  src/test/java/org/recordy/server/user/domain/UserTest.java
  src/test/java/org/recordy/server/user/repository/UserRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/user/service/UserServiceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
Labels: refactor ♻️, test 🧠

#101 [test] 1차 리팩트링 후 테스트 정리
  src/main/java/org/recordy/server/bookmark/service/impl/BookmarkServiceImpl.java
  src/main/java/org/recordy/server/preference/domain/usecase/Preference.java
  src/main/java/org/recordy/server/record/controller/RecordController.java
  src/main/java/org/recordy/server/record/service/RecordService.java
  src/main/java/org/recordy/server/record/service/impl/RecordServiceImpl.java
  src/main/java/org/recordy/server/view/domain/ViewEntity.java
  src/test/java/org/recordy/server/bookmark/domain/BookmarkEntityTest.java
  src/test/java/org/recordy/server/bookmark/repository/BookmarkRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/bookmark/service/BookmarkServiceTest.java
  src/test/java/org/recordy/server/mock/FakeContainer.java
  src/test/java/org/recordy/server/mock/record/FakeRecordRepository.java
  src/test/java/org/recordy/server/preference/domian/usercase/PreferenceTest.java
  src/test/java/org/recordy/server/preference/service/PreferenceServiceTest.java
  src/test/java/org/recordy/server/record/domain/RecordEntityTest.java
  src/test/java/org/recordy/server/record/repository/RecordRepositoryIntegrationTest.java
  src/test/java/org/recordy/server/record/service/RecordServiceTest.java
  src/test/java/org/recordy/server/record_stat/domain/usecase/PreferenceTest.java
  src/test/java/org/recordy/server/util/DomainFixture.java
  src/test/java/org/recordy/server/view/domain/ViewEntityTest.java
  src/test/java/org/recordy/server/view/repository/ViewRepositoryIntegrationTest.java
Labels: test 🧠
